spring:
#  config:
#    import: 'configserver:'
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  cloud:
    config:
      name: elastic-query-web-client,config-client
      uri: http://localhost:8888
      username: test
      password: test1234
      roles: USER
